services:
  # API Service
  - type: web
    name: hivedb-api
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: hivedb-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SGX_ENABLED
        value: false

  # Web Interface
  - type: web
    name: hivedb-web
    env: static
    buildCommand: cd web_interface && npm install && npm run build
    staticPublishPath: ./web_interface/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: hivedb-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: hivedb-db
    databaseName: hivedb
    user: hivedb
    plan: free
