name: hivedb_flutter
description: Flutter SDK for HiveDB - A secure and high-performance database inspired by beehives
version: 0.1.0
homepage: https://github.com/hivedb/hivedb_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  crypto: ^3.0.2
  logging: ^1.1.0
  connectivity_plus: ^3.0.3
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  dio: ^5.1.2
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  retry: ^3.1.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter:
  # No assets or fonts needed for this package
